{{- define "build-pipeline-docker-image-build-push-common" -}}
- name: kaniko-build
  taskRef:
    kind: Task
    name: kaniko
  runAfter:
    - dockerfile-lint
  params:
    - name: IMAGE
      value: "$(tasks.init-values.results.DOCKER_REGISTRY_HOST)/$(params.CODEBASE_NAME):$(tasks.get-version.results.IS_TAG)"
    - name: IMAGE_TAR
      value: "$(params.CODEBASE_NAME)_$(tasks.get-version.results.IS_TAG)"
    - name: KANIKO_CACHE_REPO
      value: "$(tasks.init-values.results.DOCKER_REGISTRY_HOST)/kaniko-cache"
    - name: REPO_NAME
      value: "$(tasks.init-values.results.DOCKER_REGISTRY_HOST)/$(params.CODEBASE_NAME)"

  workspaces:
    - name: source
      workspace: shared-workspace
{{- end -}}
