apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-edp-values
spec:
  results:
    - name: DOCKER_HOST_URL
      description: "docker host url"
    - name: TENANT_NAME
      description: "edp name"
  steps:
    - name: get-values
      image: bitnami/kubectl:1.24.4
      script: |
        #!/usr/bin/env bash
        set -e
        dockerRegistryHost=$(kubectl get edpcomponent docker-registry -o jsonpath='{.spec.url}')
        echo ${dockerRegistryHost} | tr -d '\n' | tee $(results.DOCKER_HOST_URL.path)
        tenantName=$(kubectl get cm edp-config -o jsonpath='{.data.edp_name}')
        echo ${tenantName} | tr -d '\n' | tee $(results.TENANT_NAME.path)
    - name: write-outputs
      image: docker.io/library/bash:5.1.4@sha256:b208215a4655538be652b2769d82e576bc4d0a2bb132144c060efc5be8c3f5d6
      script: |
        set -e
        cat $(results.DOCKER_HOST_URL.path)
        cat $(results.TENANT_NAME.path)