apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: getedp-version
spec:
  description:
  params:
    - name: CODEBASEBRANCH_NAME
      type: string
      description: Codebasebranch name
      default: "java8-maven-edp-master"
  results:
    - name: VERSION
      description: "Application version"
    - name: VSC_TAG
      description: "VCS tag"
    - name: IS_TAG
      description: "CodebaseImageStream tag"
  steps:
    - name: get-version
      image: bitnami/kubectl:1.24.4
      env:
      - name: CODEBASEBRANCH_NAME
        value: "$(params.CODEBASEBRANCH_NAME)"
      script: |
        #!/usr/bin/env bash
        set -e

        # get current BUILD ID
        BUILD_ID=$(kubectl get codebasebranches.v2.edp.epam.com ${CODEBASEBRANCH_NAME} -o txt --output=jsonpath={.status.build})
        # and increment it
        BUILD_ID=$((BUILD_ID+1))
        # set new version
        kubectl patch codebasebranches.v2.edp.epam.com ${CODEBASEBRANCH_NAME} --subresource=status --type=merge -p "{\"status\": {\"build\": \"$BUILD_ID\"}}"

        # Get current version
        VERSION=$(kubectl get codebasebranches.v2.edp.epam.com ${CODEBASEBRANCH_NAME} -o txt --output=jsonpath={.spec.version})

        echo "Application version - ${VERSION}.${BUILD_ID}"
        echo "VCS tag - build/${VERSION}"
        echo "IS tag - ${VERSION}"

        echo "${VERSION}.${BUILD_ID}" | tr -d "\n" | tee $(results.VERSION.path)
        echo "build/${VERSION}.${BUILD_ID}" | tr -d "\n" | tee $(results.VSC_TAG.path)
        echo "${VERSION}.${BUILD_ID}" | tr -d "\n" | tee $(results.IS_TAG.path)
    - name: write-outputs
      image: docker.io/library/bash:5.1.4@sha256:b208215a4655538be652b2769d82e576bc4d0a2bb132144c060efc5be8c3f5d6
      script: |
        set -e
        cat $(results.VERSION.path)
        cat $(results.VSC_TAG.path)
        cat $(results.IS_TAG.path)
