# Default values for edp-tekton.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  # -- a cluster DNS wildcard name
  dnsWildCard: "eks-sandbox.aws.main.edp.projects.epam.com"
  # -- Gerrit SSH node port
  gerritSSHPort: "30003"

# -- Tekton URL. Link to tekton Dashboard
tektonUrl: https://tekton.eks-sandbox.aws.main.edp.projects.epam.com

# Kaniko configuration section
kaniko:
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: false
  # -- AWS IAM role to be used for kaniko pod service account (IRSA). Format: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<AWS_IAM_ROLE_NAME>
  roleArn: arn:aws:iam::093899590031:role/AWSIRSACoreSandboxEdpDeliveryKaniko

gerrit:
  # -- Deploy Gerrit related components. Default: true
  enabled: true
  # -- Gerrit port
  sshPort: 30003
