# Default values for edp-tekton.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  # -- Define Git Provider to be used in Pipelines. Can be gerrit (default), gitlab, github
  gitProvider: gerrit
  # -- a cluster DNS wildcard name
  dnsWildCard: ""
  # -- Gerrit SSH node port
  gerritSSHPort: "30003"
  # -- platform type that can be "kubernetes" or "openshift"
  platform: "kubernetes"

tekton:
  # --The resource limits and requests for the Tekton Tasks
  resources:
    limits:
      cpu: "2"
      memory: "3Gi"
    requests:
      cpu: "0.5"
      memory: "2Gi"
