{{ if .Values.github.enabled }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-create-webhooks
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  params:
    - name: GitHubOrg
      default:
    - name: GitHubRepo
      default: ""
    - name: ExternalDomain
      default: ""

  tasks:
    - name: create-ingress
      taskRef:
        name: create-ingress
      params:
        - name: ExternalDomain
          value: $(params.ExternalDomain)
        - name: ServiceNamespace
          value: {{ .Release.Namespace }}
        - name: Service
          value: "el-github-listener"

    - name: create-webhook-run-for-build-pipelines
      taskRef:
        name: create-webhook
      runAfter:
        - create-ingress
      params:
        - name: GitHubOrg
          value: $(params.GitHubOrg)
        - name: GitHubRepo
          value: $(params.GitHubRepo)
        - name: ExternalDomain
          value: $(params.ExternalDomain)
        - name: WebhookEvents
          value: '[\"push\"]'

    - name: create-webhook-run-for-code-review-pipelines
      taskRef:
        name: create-webhook
      runAfter:
        - create-ingress
      params:
        - name: GitHubOrg
          value: $(params.GitHubOrg)
        - name: GitHubRepo
          value: $(params.GitHubRepo)
        - name: ExternalDomain
          value: $(params.ExternalDomain)
        - name: WebhookEvents
          value: '[\"pull_request\"]'
{{ end }}
