apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
  - ./tests/e2e/
skipClusterDelete: false
timeout: 100
parallel: 3
commands:
  # Install Cert manager which is used by Interceptor
  - command: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml
    namespaced: false
  # install EDPComponent CRD first
  - command: kubectl apply -f https://raw.githubusercontent.com/epam/edp-component-operator/master/deploy-templates/crds/v1.edp.epam.com_edpcomponents.yaml
    namespaced: false
  # install GitServer CRD
  - command: kubectl apply -f https://raw.githubusercontent.com/epam/edp-codebase-operator/master/deploy-templates/crds/v2.edp.epam.com_gitservers.yaml
    namespaced: false
  # install Tekton
  - command: kubectl create ns tekton-pipelines
    namespaced: false
  - command: kubectl create ns tekton-pipelines-resolvers
    namespaced: false
  - command: kubectl apply -f https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
    namespaced: false
  - command: kubectl apply -f https://storage.googleapis.com/tekton-releases/triggers/latest/interceptors.yaml
    namespaced: false
  - command: kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
    namespaced: false
  - command: helm dependency update ./charts/pipelines-library
    namespaced: true
  # We have all the requered checks, but let's wait a bit to make sure all the webhooks are registered
  - command: sleep 20
    namespaced: false
