apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: java11-build
spec:
  taskRunSpecs:
    - pipelineTaskName: kaniko-build
      taskServiceAccountName: edp-kaniko
  pipelineRef:
    name: maven-build-pipeline
  workspaces:
    - name: maven-settings
      configMap:
        name: custom-maven-settings
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: maven-source-pvc
      subPath: codebase
