{{ if .Values.interceptor.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-edp-interceptor
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "edp-tekton.serviceAccountName" . }}
    namespace: {{ .Values.interceptor.tektonNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-edp-interceptor
{{ end }}
