{{ if .Values.interceptor.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "edp-tekton.serviceAccountName" . }}
  namespace: {{ .Values.interceptor.tektonNamespace }}
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
  {{- with .Values.interceptor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
