{{ if .Values.interceptor.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: tekton-triggers-edp-interceptor
  namespace: {{ .Values.interceptor.tektonNamespace }}
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "edp-tekton.selectorLabels" . | nindent 4 }}
{{ end }}
