apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edp-vcluster-namespace-admin-{{ .Release.Namespace }}
  namespace: e2e-vcluster
  labels:
    {{- include "edp-custom-pipelines.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: tekton
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
