{{ if eq .Values.global.gitProvider "gitlab" }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitlab-dotnet-dotnet-6.0-app-build-default
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  workspaces:
    - name: shared-workspace
    - name: ssh-creds
  params:
    - name: pipelineUrl
      default: https://tekton-{{ .Release.Namespace }}.{{ .Values.global.dnsWildCard }}/#/namespaces/$(context.pipelineRun.namespace)/pipelineruns/$(context.pipelineRun.name)
      type: string
    - name: git-source-url
      default: "https://github.com/epmd-edp/csharp-dotnet-dotnet-6.0"
      description: git url to clone
      type: string
    - name: git-source-revision
      description: 'git revision to checkout (branch, tag, sha, ref…)'
      default: "edp"
      type: string
    - name: SONAR_URL
      default: 'http://sonar.{{ .Release.Namespace }}:9000'
      description: SonarQube url for static code analysis
      type: string
    - name: NEXUS_URL
      default: 'http://nexus.{{ .Release.Namespace }}:8081'
      description: Nexus url
      type: string
    - name: CODEBASE_NAME
      default: 'csharp-dotnet-dotnet-6.0'
      description: "Project name"
      type: string
    - name: CODEBASEBRANCH_NAME
      description: "Codebasebranch name"
      type: string
    - name: image
      default: 'mcr.microsoft.com/dotnet/sdk:6.0.407-alpine3.17'
      description: "dotnet-sdk image version"
      type: string
    - name: TICKET_NAME_PATTERN
      description: "Ticket name pattern"
      default: ""
    - name: COMMIT_MESSAGE_PATTERN
      description: "Pattern to validate a commit message"
      default: ""
    - name: COMMIT_MESSAGE
      description: "Commit message"
      default: ""
    - name: JIRA_ISSUE_METADATA_PAYLOAD
      description: "Jira Payload"
      default: ""
    - name: JIRA_SERVER
      description: "Jira server name"
      default: ""
  tasks:

{{- include "gitlab-build-start" . | nindent 4 }}

    - name: get-version
      taskRef:
        kind: Task
        name: get-version-csharp-default
      runAfter:
        - init-values
      params:
        - name: BRANCH_NAME
          value: $(params.git-source-revision)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: dotnet-build
      taskRef:
        kind: Task
        name: dotnet
      runAfter:
        - get-version
      params:
        - name: BASE_IMAGE
          value: $(params.image)
        - name: EXTRA_COMMANDS
          value: |
            dotnet build
      workspaces:
        - name: source
          workspace: shared-workspace

{{- include "dotnet-6-0-build-common" . | nindent 4 }}

    - name: dotnet-publish
      taskRef:
        kind: Task
        name: dotnet
      runAfter:
        - push
      params:
        - name: BASE_IMAGE
          value: $(params.image)
        - name: EXTRA_COMMANDS
          value: |
            set -x
            dotnet publish --configuration Release --output app
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: create-ecr-repository
      taskRef:
        kind: Task
        name: create-ecr-repository
      runAfter:
        - dotnet-publish
      params:
        - name: REPO_NAME
          value: "$(tasks.init-values.results.TENANT_NAME)/$(params.CODEBASE_NAME)"

{{ include "build-pipeline-end" . | nindent 4 }}

{{ include "finally-block-default" . | nindent 2 }}

{{ end }}
