{{ if eq .Values.global.gitProvider "gerrit" }}
{{- $resourceMapping := dict "antora" "antora/antora:3.1.4" -}}
{{- range $k, $v := $resourceMapping }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gerrit-npm-{{ $k }}-app-build-default
  labels:
    {{- include "edp-tekton.labels" $ | nindent 4 }}
spec:
  workspaces:
    - name: shared-workspace
    - name: ssh-creds
  params:
    - name: pipelineUrl
      default: https://tekton-{{ $.Release.Namespace }}.{{ $.Values.global.dnsWildCard }}/#/namespaces/$(context.pipelineRun.namespace)/pipelineruns/$(context.pipelineRun.name)
      type: string
    - name: git-source-url
      default: "https://github.com/epmd-edp/javascript-npm-{{ $k }}"
      description: git url to clone
      type: string
    - name: git-source-revision
      description: 'git revision to checkout (branch, tag, sha, ref…)'
      default: "edp"
      type: string
    - name: CODEBASE_NAME
      default: '{{ $k }}-npm-edp-version'
      description: "Project name"
      type: string
    - name: CODEBASEBRANCH_NAME
      description: "Codebasebranch name"
      type: string
    - name: image
      default: '{{ $v }}'
      description: "npm image version"
      type: string
    - name: changeNumber
      description: Change number from Merge Request
    - name: patchsetNumber
      description: Patchset number from Merge Request
    - name: TICKET_NAME_PATTERN
      description: "Ticket name pattern"
      default: ""
    - name: COMMIT_MESSAGE_PATTERN
      description: "Pattern to validate a commit message"
      default: ""
    - name: COMMIT_MESSAGE
      description: "Commit message"
      default: ""
    - name: JIRA_ISSUE_METADATA_PAYLOAD
      description: "Jira Payload"
      default: ""
    - name: JIRA_SERVER
      description: "Jira server name"
      default: ""
  tasks:

{{- include "gerrit-build-start" $ | nindent 4 }}

    - name: get-version
      taskRef:
        kind: Task
        name: get-version-npm-default
      runAfter:
        - init-values
      params:
        - name: BRANCH_NAME
          value: $(params.git-source-revision)
        - name: BASE_IMAGE
          value: $(params.image)
      workspaces:
        - name: source
          workspace: shared-workspace

{{ include "sast" . | nindent 4 }}

    - name: build
      taskRef:
        kind: Task
        name: npm
      runAfter:
        - sast
      params:
        - name: BASE_IMAGE
          value: $(params.image)
        - name: EXTRA_COMMANDS
          value: |
            upBase64=$(echo -n ${CI_USERNAME}:${CI_PASSWORD} | base64)
            npm set registry http://${NEXUS_REPOSITORY_URL}/
            npm set //${NEXUS_REPOSITORY_URL}/:email=edp-ci@edp.local
            npm set //${NEXUS_REPOSITORY_URL}/:_auth=$upBase64
            npm install
            npm run build:prod
      workspaces:
        - name: source
          workspace: shared-workspace

{{- include "build-pipeline-antora-image-build-push-common" $ | nindent 4 }}

{{ include "build-pipeline-end" . | nindent 4 }}

{{ include "finally-block-default" . | nindent 2 }}

---
{{ end }}
{{ end }}
