{{ if eq .Values.global.gitProvider "gerrit" }}
{{- $frameworks := list "fastapi" "flask" -}}
{{- range $framework := $frameworks }}
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: gerrit-python-{{ $framework }}-app-review
  labels:
    {{- include "edp-tekton.labels" $ | nindent 4 }}
spec:
  workspaces:
    - name: shared-workspace
    - name: ssh-creds
  params:
    - name: pipelineUrl
      default: https://tekton-{{ $.Release.Namespace }}.{{ $.Values.global.dnsWildCard }}/#/namespaces/$(context.pipelineRun.namespace)/pipelineruns/$(context.pipelineRun.name)
      type: string
    - name: git-source-url
      default: "https://github.com/epmd-edp/python-python-python-3.8"
      description: git url to clone
      type: string
    - name: git-source-revision
      description: 'git revision to checkout (branch, tag, sha, ref…)'
      default: "edp"
      type: string
    - name: git-refspec
      description: Refspec to fetch before checking out revision.
      default: ""
      type: string

    - name: CODEBASE_NAME
      default: "python-app"
      description: "Project name"
      type: string
    - name: targetBranch
      description: Target branch of Merge Request
    - name: changeNumber
      description: Change number from Merge Request
    - name: patchsetNumber
      description: Patchset number from Merge Request
    - name: CHART_DIR
      description: "Deploy templates directory for helm-lint"
      default: "deploy-templates"
    - name: CT_CONFIGS_DIR
      description: "ct-configs directory for helm-lint"
      default: "."
  tasks:

{{- include "gerrit-review-start" $ | nindent 4 }}

{{- include "helm-docs" $ | nindent 4 }}

    - name: python
      taskRef:
        kind: Task
        name: python
      runAfter:
        - init-values
      params:
        - name: EXTRA_COMMANDS
          value: |
            # build
            python setup.py clean build install --user
            # lint
            pip3 install -r test-requirements.txt
            pylint --output-format=colorized *.py
            flake8 --exclude .local --filename=*.py
            # test
            pytest -sv --color=yes
      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source

    # The fetch-target-branch Task will fetch the target branch during the code-review pipeline
    # because the fetch-repository Task fetches only user changes.
    - name: fetch-target-branch
      taskRef:
        kind: Task
        name: git-cli
      runAfter:
        - python
      params:
        - name: GIT_USER_EMAIL
          value: edp-ci@edp.ci-user
        - name: GIT_USER_NAME
          value: edp-ci
        - name: GIT_SCRIPT
          value: |
            git fetch origin $(params.targetBranch):refs/remotes/origin/$(params.targetBranch)
      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source
        - name: ssh-directory
          workspace: ssh-creds

    - name: sonar-prepare-files
      taskRef:
        kind: Task
        name: sonar-prepare-files-general
      runAfter:
        - fetch-target-branch
      params:
        - name: CODEBASE_NAME
          value: $(params.CODEBASE_NAME)
        - name: BRANCH_NAME
          value: $(params.targetBranch)
        - name: NORMALIZED_BRANCH
          value: $(tasks.init-values.results.NORMALIZED_BRANCH)
        - name: CHANGE_NUMBER
          value: $(params.changeNumber)
        - name: PATCHSET_NUMBER
          value: $(params.patchsetNumber)
      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source

    - name: sonar
      taskRef:
        kind: Task
        name: sonarqube-scanner
      runAfter:
        - sonar-prepare-files
      params:
        - name: SONAR_PROJECT_KEY
          value: $(tasks.sonar-prepare-files.results.SONAR_PROJECT_KEY)
        - name: SONAR_PROJECT_NAME
          value: $(tasks.sonar-prepare-files.results.SONAR_PROJECT_KEY)
        - name: SONAR_SOURCES
          value: $(tasks.sonar-prepare-files.results.SONAR_SOURCES)
      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source

    - name: dockerfile-lint
      taskRef:
        kind: Task
        name: hadolint
      runAfter:
        - sonar
      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source

{{ include "dockerbuild-verify-python" $ | nindent 4 }}

    - name: helm-lint
      taskRef:
        kind: Task
        name: helm-lint
      runAfter:
        - sonar
      params:
        - name: CHART_DIR
          value: $(params.CHART_DIR)
        - name: CT_CONFIGS_DIR
          value: $(params.CT_CONFIGS_DIR)
      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source

{{ include "gerrit-review-vote" $ | nindent 2 }}

---
{{- end }}
{{ end }}
