{{ if .Values.github.enabled }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-npm-react-lib-review
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  workspaces:
    - name: shared-workspace
    - name: ssh-creds
  params:
    - name: pipelineUrl
      default: https://tekton.{{ .Values.global.dnsWildCard }}/#/namespaces/$(context.pipelineRun.namespace)/pipelineruns/$(context.pipelineRun.name)
      type: string
    - name: git-source-url
      default: "https://github.com/epmd-edp/javascript-npm-react"
      description: git url to clone
      type: string
    - name: git-source-revision
      description: 'git revision to checkout (branch, tag, sha, ref…)'
      default: "edp"
      type: string
    - name: git-refspec
      description: Refspec to fetch before checking out revision.
      default: ""
      type: string
    - name: SONAR_URL
      default: 'http://sonar.{{ .Release.Namespace }}:9000'
      description: SonarQube url for static code analysis
      type: string
    - name: NEXUS_URL
      default: 'http://nexus.{{ .Release.Namespace }}:8081'
      description: Nexus url
      type: string
    - name: CODEBASE_NAME
      default: 'react-npm-edp-version'
      description: "Project name"
      type: string
    - name: npm-image-version
      default: 'docker.io/library/node:18.10-alpine3.16'
      description: "npm image version"
      type: string
    - name: gitfullrepositoryname
      description: "repository full name"
      type: string
    - name: gitsha
      description: "commit sha"
      type: string
  tasks:

    - name: github-set-pending-status
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.gitfullrepositoryname)
        - name: DESCRIPTION
          value: "Build has started"
        - name: STATE
          value: "pending"
        - name: AUTH_TYPE
          value: Token
        - name: GITHUB_TOKEN_SECRET_NAME
          value: {{ .Values.github.webhook.existingSecret }}
        - name: GITHUB_TOKEN_SECRET_KEY
          value: {{ .Values.github.webhook.secretKeys.tokenKey }}
        - name: SHA
          value: $(params.gitsha)
        - name: TARGET_URL
          value: $(params.pipelineUrl)

    - name: fetch-repository
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-source-url)
        - name: revision
          value: $(params.git-source-revision)
        - name: refspec
          value: $(params.git-refspec)
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: ssh-directory
          workspace: ssh-creds

    - name: init-values
      taskRef:
        name: init-values
      runAfter:
        - fetch-repository
      params:
        - name: CODEBASE_NAME
          value: $(params.CODEBASE_NAME)
        - name: BRANCH_NAME
          value: $(params.git-source-revision)

    - name: compile
      taskRef:
        name: npm
      runAfter:
        - init-values
      params:
        - name: BASE_IMAGE
          value: $(params.npm-image-version)
        - name: EXTRA_COMMANDS
          value: |
            upBase64=$(echo -n ${CI_USERNAME}:${CI_PASSWORD} | base64)
            npm set registry http://nexus:8081/repository/edp-npm-group/ --location project
            npm set //nexus:8081/repository/edp-npm-group/:always-auth true --location project
            npm set //nexus:8081/repository/edp-npm-group/:email edp-ci@edp.local --location project
            npm set //nexus:8081/repository/edp-npm-group/:_auth $upBase64 --location project
            npm install
            npm run build:clean
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: test
      taskRef:
        name: npm
      runAfter:
        - compile
      params:
        - name: BASE_IMAGE
          value: $(params.npm-image-version)
        - name: EXTRA_COMMANDS
          value: |
            npm run test:coverage
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: sonar
      taskRef:
        name: sonarqube-scanner
      runAfter:
        - test
      params:
        - name: SONAR_HOST_URL
          value: $(params.SONAR_URL)
        - name: SONAR_PROJECT_KEY
          value: $(tasks.init-values.results.CODEBASEBRANCH_NAME)
        - name: SONAR_PROJECT_NAME
          value: $(tasks.init-values.results.CODEBASEBRANCH_NAME)
      workspaces:
        - name: source
          workspace: shared-workspace

  finally:
    - name: github-set-success-status
      when:
        - input: "$(tasks.status)"
          operator: in
          values: ["Succeeded"]
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.gitfullrepositoryname)
        - name: DESCRIPTION
          value: "Build was successful"
        - name: STATE
          value: "success"
        - name: AUTH_TYPE
          value: Token
        - name: GITHUB_TOKEN_SECRET_NAME
          value: {{ .Values.github.webhook.existingSecret }}
        - name: GITHUB_TOKEN_SECRET_KEY
          value: {{ .Values.github.webhook.secretKeys.tokenKey }}
        - name: SHA
          value: $(params.gitsha)
        - name: TARGET_URL
          value: $(params.pipelineUrl)

    - name: github-set-failure-status
      when:
        - input: "$(tasks.status)"
          operator: in
          values: ["Failed"]
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.gitfullrepositoryname)
        - name: DESCRIPTION
          value: "Build has failed"
        - name: STATE
          value: "failure"
        - name: AUTH_TYPE
          value: Token
        - name: GITHUB_TOKEN_SECRET_NAME
          value: {{ .Values.github.webhook.existingSecret }}
        - name: GITHUB_TOKEN_SECRET_KEY
          value: {{ .Values.github.webhook.secretKeys.tokenKey }}
        - name: SHA
          value: $(params.gitsha)
        - name: TARGET_URL
          value: $(params.pipelineUrl)

{{ end }}
