apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-source-pvc
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
