apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: sam
spec:
  params:
    - default: public.ecr.aws/sam/build-python3.9:1.104.0-20231206215146
      description: The base image for the task.
      name: BASE_IMAGE
      type: string
    - name: EXTRA_COMMANDS
      type: string
      description: Extra commands
      default: ""
  steps:
    - computeResources: {}
      image: $(params.BASE_IMAGE)
      name: sam-build
      script: |
        set -ex

        $(params.EXTRA_COMMANDS)
      workingDir: $(workspaces.source.path)
  workspaces:
    - description: A workspace that contains fetched git repo.
      name: source