apiVersion: v1
kind: ServiceAccount
metadata:
  name: edp-kaniko
  namespace: tekton-pipelines
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::093899590031:role/AWSIRSACoreSandboxEdpDeliveryKaniko

