{{ if .Values.gerrit.enabled }}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: gerrit-code-review-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gerritproject
      description: Gerrit project name
    - name: gerritrefspec
      description: Gerrit PatchSet Reference in format "refs/changes/62/62/2"
    - name: buildtool
      description: Build tool for codebase. Used to generate code-review pipeline name. Populated by edp interceptor
    - name: framework
      description: Framework for codebase. Used to generate code-review pipeline name. Populated by edp interceptor
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.gerritproject)-review-
      spec:
        serviceAccountName: jenkins
        pipelineRef:
          name: gerrit-$(tt.params.buildtool)-$(tt.params.framework)-review
        params:
          - name: git-source-url
            value: "ssh://jenkins@gerrit:{{ .Values.gerrit.sshPort }}/$(tt.params.gerritproject)"
          - name: git-source-revision
            value: $(tt.params.gitrevision)
          - name: git-refspec
            value: $(tt.params.gerritrefspec)
          - name: CODEBASE_NAME
            value: $(tt.params.gerritproject)
        workspaces:
          - name: settings
            configMap:
              name: custom-$(tt.params.buildtool)-settings
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
            subPath: codebase
          - name: ssh-creds
            secret:
              secretName: gerrit-ciuser-sshkey
{{ end }}
