{{ if .Values.gitlab.enabled }}
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitlab-listener
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  triggers:
    - name: gitlab-listener-build
      interceptors:
        - ref:
            name: "gitlab"
          params:
            - name: "secretRef"
              value:
                secretName: gitlab-webhook-secret
                secretKey: secret
            - name: "eventTypes"
              value: ["Merge Request Hook"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.object_attributes.action in ['merge']"
        - ref:
            name: "edp"
      bindings:
        - ref: gitlab-binding-build
      template:
        ref: gitlab-build-template

    - name: gitlab-listener-code-review
      interceptors:
        - ref:
            name: "gitlab"
          params:
            - name: "secretRef"
              value:
                secretName: gitlab-webhook-secret
                secretKey: secret
            - name: "eventTypes"
              value: ["Merge Request Hook"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.object_attributes.action in ['open', 'reopen', 'update']"
        - ref:
            name: "edp"
      bindings:
        - ref: gitlab-binding-review
      template:
        ref: gitlab-code-review-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-sa-{{ .Release.Namespace }}
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "50m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
{{ end }}
