{{ if eq .Values.global.gitProvider "gitlab" }}
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitlab-listener
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  triggers:
    - name: gitlab-listener-build
      interceptors:
        - ref:
            name: "gitlab"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.gitlab.webhook.existingSecret }}
                secretKey: secretString
            - name: "eventTypes"
              value: ["Merge Request Hook"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.object_attributes.action in ['merge']"
        - ref:
            name: "edp"
            kind: NamespacedInterceptor
        - ref:
            name: "cel"
          params:
            - name: "overlays"
              value:
              - key: cbtype_short
                expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: gitlab-binding-build
      template:
        ref: gitlab-build-template

    - name: gitlab-listener-review
      interceptors:
        - ref:
            name: "gitlab"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.gitlab.webhook.existingSecret }}
                secretKey: secretString
            - name: "eventTypes"
              value: ["Merge Request Hook", "Note Hook"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.object_attributes.action in ['open', 'reopen', 'update'] || (body.object_kind == 'note' && has(body.merge_request))"
        - ref:
            name: "edp"
            kind: NamespacedInterceptor
        - ref:
            name: "cel"
          params:
            - name: "overlays"
              value:
              - key: cbtype_short
                expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: gitlab-binding-review
      template:
        ref: gitlab-review-template

  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-sa-{{ .Release.Namespace }}
            containers:
              - name: ''
                resources:
                  {{- toYaml .Values.eventListener.resources | nindent 18 }}
{{ end }}
