{{ if .Values.gitlab.enabled }}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: gitlab-code-review-template
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
    - name: gitrepositoryname
    - name: gitfullrepositoryname
      description: Full Repo name. Used in "gitlab-set-status" step as REPO_PATH_ONLY
    - name: buildtool
      description: Build tool for codebase. Used to generate build pipeline name. Populated by edp interceptor
    - name: framework
      description: Framework for codebase. Used to generate build pipeline name. Populated by edp interceptor
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.gitrepositoryname)-review-
      spec:
        serviceAccountName: jenkins
        taskRunSpecs:
          - pipelineTaskName: create-ecr-repository
            taskServiceAccountName: edp-kaniko
          - pipelineTaskName: kaniko-build
            taskServiceAccountName: edp-kaniko
        pipelineRef:
          name: gitlab-$(tt.params.buildtool)-$(tt.params.framework)-review
        params:
          - name: git-source-url
            value: $(tt.params.gitrepositoryurl)
          - name: git-source-revision
            value: $(tt.params.gitrevision)
          - name: CODEBASE_NAME
            value: $(tt.params.gitrepositoryname)
          - name: gitfullrepositoryname
            value: $(tt.params.gitfullrepositoryname)
        workspaces:
          - name: settings
            configMap:
              name: custom-$(tt.params.buildtool)-settings
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
            subPath: codebase
          - name: ssh-creds
            secret:
              secretName: gitlab-sshkey
{{ end }}
