{{ if eq .Values.global.gitProvider "gerrit" }}
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: edp
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  triggers:
    - name: gerrit-listener-build
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.change.status in ['MERGED']"
        - ref:
            name: "edp"
            kind: NamespacedInterceptor
        - ref:
            name: "cel"
          params:
            - name: "overlays"
              value:
              - key: cbtype_short
                expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: gerrit-binding-build
      template:
        ref: gerrit-build-template

    - name: gerrit-listener-review
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.change.status in ['NEW']"
        - ref:
            name: "edp"
            kind: NamespacedInterceptor
        - ref:
            name: "cel"
          params:
            - name: "overlays"
              value:
                - key: cbtype_short
                  expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: gerrit-binding-review
      template:
        ref: gerrit-review-template

  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-sa-{{ .Release.Namespace }}
            containers:
              - name: ''
                resources:
                  {{- toYaml .Values.eventListener.resources | nindent 18 }}
{{ end }}
