{{ if .Values.gerrit.enabled }}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gerrit-binding-build
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  params:
    - name: gitrevision
      value: "$(body.change.branch)"
    - name: gerritproject
      value: "$(body.change.project)"
    - name: buildtool
      value: "$(extensions.spec.buildTool)"
    - name: framework
      value: "$(extensions.spec.framework)"
    # Truncated cbtype type name to reduce string length
    - name: cbtype
      value: "$(extensions.cbtype_short)"
    - name: versioning-type
      value: "$(extensions.spec.versioning.type)"
    - name: changeNumber
      value: "$(body.change.number)"
    - name: patchsetNumber
      value: "$(body.patchSet.number)"
{{ end }}
