apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-version-npm-default
spec:
  description:
  workspaces:
    - name: source
      description: The workspace consisting of maven project.
  params:
    - name: BRANCH_NAME
      type: string
      description: Codebasebranch name
    - name: BASE_IMAGE
      description: "The base image for the task"
      default: "node:18.9.0"
  results:
    - name: VERSION
      description: "Application version"
    - name: VCS_TAG
      description: "VCS tag"
    - name: IS_TAG
      description: "CodebaseImageStream tag"
    - name: DEPLOYABLE_MODULE_DIR
    - name: TIMESTAMP
      description: Current timestamp
  steps:
    - name: get-timestamp
      image: bash:5.1.16-alpine3.15
      script: |
        #!/usr/bin/env bash
        ts=$(date "+%Y%m%d-%H%M%S")
        echo "Current Timestamp: ${ts}"
        echo ${ts} | tr -d "\n" | tee $(results.TIMESTAMP.path)

    - name: get-version
      image: $(params.BASE_IMAGE)
      env:
        - name: BRANCH_NAME
          value: "$(params.BRANCH_NAME)"
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -e

        VERSION=$(node -p "require('./package.json').version")

        # get current BUILD ID
        BUILD_ID=$(cat $(results.TIMESTAMP.path))

        BUILD_VERSION="${VERSION}-${BUILD_ID}"
        VCS_TAG="${BRANCH_NAME}-${BUILD_VERSION}"
        IS_TAG=${VCS_TAG}

        npm --no-git-tag-version version ${BUILD_VERSION}

        echo "Application version - ${VERSION}"
        echo "VCS tag - ${VCS_TAG}"
        echo "IS tag - ${IS_TAG}"

        printf "%s" "${VERSION}" > "$(results.VERSION.path)"
        printf "%s" "${VCS_TAG}" > "$(results.VCS_TAG.path)"
        printf "%s" "${IS_TAG}" > "$(results.IS_TAG.path)"

        DEPLOYABLE_MODULE_DIR="."

        printf "%s" "${DEPLOYABLE_MODULE_DIR}" > "$(results.DEPLOYABLE_MODULE_DIR.path)"
