apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-build-number-maven-default
spec:
  description: >-
    This Task can be used to update an application version.

  workspaces:
    - name: source
      description: The workspace consisting of maven project.
  params:
    - name: VERSION
      type: string
    - name: ci-nexus
      type: string
      description: name of the secret for the Nexus integration
      default: ci-nexus
    - name: BASE_IMAGE
      description: "The base image for the task"
  volumes:
    - name: settings-maven
      configMap:
        name: custom-maven-settings
  steps:
    - name: update-build-number
      image: $(params.BASE_IMAGE)
      volumeMounts:
        - name: settings-maven
          mountPath: /var/configmap
      {{- if .Values.tekton.packageRegistriesSecret.enabled }}
      envFrom:
      - secretRef:
          name: {{ .Values.tekton.packageRegistriesSecret.name }}
      {{- end }}
      workingDir: $(workspaces.source.path)
      env:
        - name: VERSION
          value: "$(params.VERSION)"
        - name: CI_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.ci-nexus)
              key: username
        - name: CI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.ci-nexus)
              key: password
      script: |
        set -ex

        /usr/bin/mvn \
        -s \
        /var/configmap/settings.xml \
        -B \
        versions:set \
        versions:commit \
        -DnewVersion=${VERSION}
