apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-build-number-dotnet
spec:
  description:
  workspaces:
    - name: source
      description: The workspace consisting of maven project.
  params:
    - name: VERSION
      type: string
      description: "Version"
    - name: BASE_IMAGE
      description: "The base image for the task"
      default: "bash:5.1.16-alpine3.15"
  steps:
    - name: update-build-number
      image: $(params.BASE_IMAGE)
      workingDir: $(workspaces.source.path)
      env:
        - name: VERSION
          value: "$(params.VERSION)"
      script: |
        #!/usr/bin/env bash
        set -exo pipefail

        apk add --no-cache grep
        DEPLOYABLE_MODULE=$(find ./ -name '*.csproj' | xargs grep -Poh '<DeployableModule>\K[^<]*')

        sed -i "s#\(<Version>\).*\(</Version>\)#\1${VERSION}\2#" ${DEPLOYABLE_MODULE}/${DEPLOYABLE_MODULE}.csproj
