{{- range .Values.gitServers }}
{{- if has .gitProvider $.Values.global.gitProviders }}
apiVersion: v2.edp.epam.com/v1
kind: GitServer
metadata:
  name: {{ .name }}
  labels:
    {{- include "edp-tekton.labels" $ | nindent 4 }}
spec:
  gitHost: {{ .host }}
  gitProvider: {{ .gitProvider }}
  gitUser: git
  httpsPort: 443
  nameSshKeySecret: {{ printf "ci-%s" .gitProvider | quote }}
  sshPort: 22
  skipWebhookSSLVerification: {{ .webhook.skipWebhookSSLVerification }}
{{- end }}
---
{{- end }}
