{{- range $name, $server := .Values.gitServers }}
{{- if has $server.gitProvider $.Values.global.gitProviders }}
apiVersion: v2.edp.epam.com/v1
kind: GitServer
metadata:
  name: {{ $name }}
  labels:
    {{- include "edp-tekton.labels" $ | nindent 4 }}
spec:
  gitHost: {{ $server.host }}
  gitProvider: {{ $server.gitProvider }}
  gitUser: git
  httpsPort: 443
  nameSshKeySecret: {{ printf "ci-%s" $server.gitProvider | quote }}
  sshPort: 22
  skipWebhookSSLVerification: {{ $server.webhook.skipWebhookSSLVerification }}
{{- end }}
---
{{- end }}
