{{- if eq .Values.global.platform "kubernetes" }}
{{- $root := $ -}}
{{- range $name, $server := .Values.gitServers }}
{{- if and (has $server.gitProvider $.Values.global.gitProviders) $server.eventListener.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-listener-{{ $server.gitProvider }}
  labels:
    {{- include "edp-tekton.labels" $root | nindent 4 }}
  annotations:
    {{- with $server.eventListener.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{- if $server.eventListener.ingress.tls }}
  tls:
    {{- range $server.eventListener.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
{{- end }}
  rules:
    - host: el-{{ $server.gitProvider }}-{{ $root.Release.Namespace }}.{{ $root.Values.global.dnsWildCard }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # The service name will come from EventListener CR
                name: el-edp-{{ $server.gitProvider }}
                port:
                  number: 8080
{{- end }}
---
{{- end }}
{{- end }}
