{{ if eq .Values.global.gitProvider "github" }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-gradle-java8-app-build-default
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  workspaces:
    - name: shared-workspace
    - name: ssh-creds
  params:
    - name: git-source-url
      default: "https://github.com/sergk/spring-petclinic"
      description: git url to clone
      type: string
    - name: git-source-revision
      description: 'git revision to checkout (branch, tag, sha, ref…)'
      default: "edp"
      type: string
    - name: SONAR_URL
      default: 'http://sonar.{{ .Release.Namespace }}:9000'
      description: SonarQube url for static code analysis
      type: string
    - name: NEXUS_URL
      default: 'http://nexus.{{ .Release.Namespace }}:8081'
      description: Nexus url
      type: string
    - name: CODEBASE_NAME
      default: 'java8-gradle'
      description: "Project name"
      type: string
    - name: CODEBASEBRANCH_NAME
      description: "Codebasebranch name"
      type: string
    - name: gradle-image-version
      default: 'gradle:7.5.1-jdk8'
      description: "gradle image version"
      type: string
  tasks:

{{- include "github-build-start" . | nindent 4 }}

    - name: get-version
      taskRef:
        name: get-version-gradle-default
      runAfter:
        - init-values
      params:
        - name: BRANCH_NAME
          value: $(params.git-source-revision)
        - name: NEXUS_URL
          value: $(params.NEXUS_URL)
        - name: BASE_IMAGE
          value: $(params.gradle-image-version)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: sast
      taskRef:
        name: sast
      runAfter:
        - fetch-repository
      params:
        - name: reportDataProductName
          value: $(tasks.init-values.results.TENANT_NAME)
        - name: reportDataEngagementName
          value: $(params.CODEBASEBRANCH_NAME)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: compile
      taskRef:
        name: gradle
      runAfter:
        - get-version
      params:
        - name: BASE_IMAGE
          value: $(params.gradle-image-version)
        - name: EXTRA_ARGS
          value: |
            -PnexusMavenRepositoryUrl=$(params.NEXUS_URL)/repository/edp-maven-group \
            clean \
            compileJava \
            -x test
      workspaces:
        - name: source
          workspace: shared-workspace

{{ include "java-gradle-build-common" . | nindent 4 }}

    - name: create-ecr-repository
      taskRef:
        name: create-ecr-repository
      runAfter:
        - push
      params:
        - name: REPO_NAME
          value: "$(tasks.init-values.results.TENANT_NAME)/$(params.CODEBASE_NAME)"

{{ include "build-pipeline-end" . | nindent 4 }}

{{ end }}
