# Default values for edp-tekton.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  # -- a cluster DNS wildcard name
  dnsWildCard: "eks-sandbox.aws.main.edp.projects.epam.com"

# Kaniko configuration section
kaniko:
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: false
  # -- AWS IAM role to be used for kaniko pod service account (IRSA). Format: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<AWS_IAM_ROLE_NAME>
  roleArn: arn:aws:iam::093899590031:role/AWSIRSACoreSandboxEdpDeliveryKaniko

github:
  enabled: true
  accountName: "GitHub Account Name"
  repositoryName: "GitHub Repository Name"
  webhookSecret:
    token: "123"
    secretString: "random-string-data"

tekton:
  # Pruner provides auto clean up feature for the Tekton resources
  pruner:
    # -- Specifies whether a cronjob should be created
    create: true
    # -- How often to clean up resources
    schedule: "0 18 * * *"
    # -- Maximum number of resources to keep while deleting removing
    keep: 1
    # -- Supported resources for auto prune are 'taskrun' and 'pipelinerun'
    resources: "pipelinerun,taskrun"
