# Default values for edp-tekton.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  # -- a cluster DNS wildcard name
  dnsWildCard: "eks-sandbox.aws.main.edp.projects.epam.com"

# Kaniko configuration section
kaniko:
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: false
  # -- AWS IAM role to be used for kaniko pod service account (IRSA). Format: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<AWS_IAM_ROLE_NAME>
  roleArn: arn:aws:iam::093899590031:role/AWSIRSACoreSandboxEdpDeliveryKaniko

gerrit:
  # -- Deploy Gerrit related components. Default: true
  enabled: true
  # -- Gerrit port
  sshPort: 30003

github:
  enabled: false
  accountName: "GitHub Account Name"
  repositoryName: "GitHub Repository Name"
  webhookSecret:
    token: "123"
    secretString: "random-string-data"

gitlab:
  enabled: false
  # -- The GitLab host, adjust this if you run a GitLab enterprise. Default: gitlab.com
  host: git.epam.com
  repositoryName: "epmd-edp/temp/tekton-petclinic"
  webhookSecret:
    # -- Generated on GitLab side in section: User Settings > Access Token
    token: "generated_on_gitlab_side"
    # -- Generated on Tekton side and populated in GitLab for each Project in section: PROJECT_NAME > Settings > Webhooks > Secret Token
    secretString: "random-string-data-123"

tekton:
  # Pruner provides auto clean up feature for the Tekton resources
  pruner:
    # -- Specifies whether a cronjob should be created
    create: true
    # -- How often to clean up resources
    schedule: "0 18 * * *"
    # -- Maximum number of resources to keep while deleting removing
    keep: 1
    # -- Supported resources for auto prune are 'taskrun' and 'pipelinerun'
    resources: "pipelinerun,taskrun"

# EDP Interceptor configuration section
interceptor:
  # -- We should deploy only one instance of interceptor per cluster
  deploy: false

  # -- The namespace which contains tekton-pipelines, default: tekton-pipelines
  tektonNamespace: tekton-pipelines

  image:
    repository: sergk/edp-interceptor
    pullPolicy: IfNotPresent
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: "2"

  imagePullSecrets: []

  serviceAccount:
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use.
    # -- If not set, a name is generated using the fullname template
    name: "edp-interceptor"

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
