apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: codenarc
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/displayName: Codenarc
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >-
    This Task can be used to run a Gradle build.

  workspaces:
    - name: source
      description: The workspace consisting of the gradle project.
    - name: gradle-settings
      description: >-
        The workspace consisting of the custom gradle settings
        provided by the user.
  params:
    - name: BASE_IMAGE
      description: Gradle base image.
      type: string
      default: gradle:7.5.1-jdk11
    - name: PROJECT_DIR
      description: The directory containing build.gradle
      type: string
      default: "."
    - name: ci-secret
      type: string
      description: name of the secret holding the CI maven secret
      default: nexus-ci.user
    - name: EXTRA_ARGS
      description: Extra arguments to add to the gradle build
      default: |
        -Dorg.gradle.internal.publish.checksums.insecure=true \
        publish
  steps:
    - name: gradle-tasks
      image: $(params.BASE_IMAGE)
      workingDir: $(workspaces.source.path)/$(params.PROJECT_DIR)
      script: |
        #!/bin/bash
        set -e

        gradle \
          -I \
          $(workspaces.gradle-settings.path)/init.gradle \
          -PnexusLogin=${CI_USERNAME} \
          -PnexusPassword=${CI_PASSWORD} \
          $(params.EXTRA_ARGS)
      env:
        - name: CI_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.ci-secret)
              key: username
        - name: CI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.ci-secret)
              key: password
    - name: codenarc-report
      image: alpine:3.16.2
      workingDir: $(workspaces.source.path)/$(params.PROJECT_DIR)
      script: |
        cat /workspace/source/build/reports/codenarc/main.html