apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/categories: Code Quality
    tekton.dev/displayName: Helm-Docs
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: linux/amd64
  name: helm-docs
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  params:
    - name: BASE_IMAGE
      description: The base image for the task.
      default: jnorwood/helm-docs:v1.11.0@sha256:e438eb9f879e4bb8389ce4acd0f7e9193e3d62e877a1a3cd5abd0393dbe55fe5
  workspaces:
    - description: A workspace that contains fetched git repo.
      name: source
  steps:
    - image: $(params.BASE_IMAGE)
      name: helm-docs
      script: |
        #!/bin/sh
        set -ex

        helmDocsReadme="deploy-templates/README.md"

        [ -f "${helmDocsReadme}" ] || (echo "The ${helmDocsReadme} file was not found. Run helm-docs to address the issue."; exit 1)
        cp ${helmDocsReadme} ${helmDocsReadme}.orig
        helm-docs
        diff ${helmDocsReadme} ${helmDocsReadme}.orig || \
            (echo "The ${helmDocsReadme} file was not updated. Run 'helm-docs' to address the issue."; exit 1)
      workingDir: $(workspaces.source.path)
