apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: python
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >-
    This task can be used to run python goals on a project.
    It utilizes default PIP and Twine environment variables.
    Twine logs in to nexus using environment variables to upload packages.
    PIP does not support username and password environment variables yet.
    Thus, we use the ~/.netrc file for PIP to download packages.
    The ~/.config/pip/pip.conf file can also be used along with ~/.netrc.
  workspaces:
    - name: source
  params:
    - name: PATH_CONTEXT
      type: string
      default: "."
      description: The path where package.json of the project is defined.
    - name: PIP_TRUSTED_HOST
      type: string
      default: ""
      description: Nexus Repository host PIP connects to via HTTP. e.g. 'nexus'
    - name: PIP_INDEX
      type: string
      default: ""
      description: >-
        Private repo index PIP searches through. It is used by 'pip search' command.
        e.g. 'http://nexus:8081/repository/edp-python-group/pypi'
    - name: PIP_INDEX_URL
      type: string
      default: ""
      description: >-
        Repo index from wich PIP downloads private packages and public packages via proxy.
        PIP_INDEX_URL can have only one URL while PIP_EXTRA_INDEX_URL can hold
        multiple URLs if passed with spaces. It is used by 'pip install' command.
        To access index via web, add slash at the end of 'simple/'.
        e.g. 'http://nexus:8081/repository/edp-python-group/simple'
    - name: TWINE_REPOSITORY_URL
      type: string
      default: ""
      description: Nexus Repository URL Twine uploads to.
    - name: TWINE_NON_INTERACTIVE
      type: string
      default: "1"
      description: Do not interactively prompt for credentials if they are missing.
    - name: EXTRA_COMMANDS
      type: string
    - name: BASE_IMAGE
      type: string
      default: "python:3.8-slim"
      description: The python image you want to use.
    - name: ci-secret
      type: string
      description: name of the secret holding the CI npm secret
      default: nexus-ci.user
    - name: NEXUS_URL
      type: string
      description: Nexus URL
      default: ""
  steps:
    - name: python
      image: $(params.BASE_IMAGE)
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
      env:
        - name: HOME
          value: $(workspaces.source.path)
        - name: PIP_TRUSTED_HOST
          value: $(params.PIP_TRUSTED_HOST)
        - name: PIP_INDEX
          value: $(params.PIP_INDEX)
        - name: PIP_INDEX_URL
          value: $(params.PIP_INDEX_URL)
        - name: TWINE_REPOSITORY_URL
          value: $(params.TWINE_REPOSITORY_URL)
        - name: TWINE_NON_INTERACTIVE
          value: $(params.TWINE_NON_INTERACTIVE)
        - name: TWINE_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.ci-secret)
              key: username
        - name: TWINE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.ci-secret)
              key: password
        - name: NEXUS_URL
          value: $(params.NEXUS_URL)
      script: |
        #!/usr/bin/env sh
        set -ex
        export PATH=$PATH:$HOME/.local/bin

        if [ -z "${PIP_TRUSTED_HOST}" ]; then
            export PIP_TRUSTED_HOST=$(echo "${NEXUS_URL}" | cut -d '/' -f 3 | cut -d ':' -f 1)
        fi

        if [ -z "${PIP_INDEX}" ]; then
            export PIP_INDEX="${NEXUS_URL}/repository/edp-python-group/pypi"
        fi

        if [ -z "${PIP_INDEX_URL}" ]; then
            export PIP_INDEX_URL="${NEXUS_URL}/repository/edp-python-group/simple"
        fi

        echo "[TEKTON][INFO] PIP_INDEX contain ${PIP_INDEX}"
        echo "[TEKTON][INFO] PIP_INDEX_URL contain ${PIP_INDEX_URL}"
        echo "[TEKTON][INFO] PIP_TRUSTED_HOST contain ${PIP_TRUSTED_HOST}"

        netcr_file="$HOME/.netrc"
        if [ ! -f "${netcr_file}" ]; then
          cat <<-EOF > "${netcr_file}"
        machine ${PIP_TRUSTED_HOST}
        login ${TWINE_USERNAME}
        password ${TWINE_PASSWORD}
        EOF
        chmod 0600 "${netcr_file}"
        fi

        $(params.EXTRA_COMMANDS)
{{- include "resources" . | nindent 6 }}
