apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-nexus-repository-url
spec:
  description: |
    This Task gets the version of an application if the version contains the 'SNAPSHOT' substring in the name
    then edp-<Tool>-snapshots Nexus repository is used else edp-<Tool>-releases Nexus repository is used.

  params:
    - name: VERSION
      type: string
      description: "Application version"
    - name: ci-nexus
      type: string
      description: name of the secret holding the Nexus CI integration data
      default: "ci-nexus"
    - name: TOOL
      type: string
      description: "Application language"
  results:
    - name: NEXUS_REPOSITORY_URL
      description: "Parameter has '<NEXUS_HOST_URL>/repository/edp-<Tool>-snapshots' or '<NEXUS_HOST_URL>/repository/edp-<Tool>-releases' value"
  steps:
    - name: get-nexus-repository-url
      image: alpine:3.18.6
      env:
        - name: VERSION
          value: "$(params.VERSION)"
        - name: NEXUS_HOST_URL
          valueFrom:
            secretKeyRef:
              name: $(params.ci-nexus)
              key: url
        - name: TOOL
          value: "$(params.TOOL)"
      script: |
        set -ex

        # Get Nexus repository name
        versionLowerCase=$(echo ${VERSION} | tr '[:upper:]' '[:lower:]')

        if [[ "$versionLowerCase" == *"snapshot"* ]]; then
            NEXUS_REPOSITORY_URL="${NEXUS_HOST_URL}/repository/edp-${TOOL}-snapshots"
        else
            NEXUS_REPOSITORY_URL="${NEXUS_HOST_URL}/repository/edp-${TOOL}-releases"
        fi

        echo "Nexus repository url- ${NEXUS_REPOSITORY_URL}"
        printf "%s" "${NEXUS_REPOSITORY_URL}" > "$(results.NEXUS_REPOSITORY_URL.path)"
