{{ if eq .Values.global.gitProvider "gitlab" }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitlab-maven-java11-lib-build-default
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  workspaces:
    - name: shared-workspace
    - name: ssh-creds
  params:
    - name: git-source-url
      default: "https://github.com/sergk/spring-petclinic"
      description: git url to clone
      type: string
    - name: git-source-revision
      description: 'git revision to checkout (branch, tag, sha, ref…)'
      default: "edp"
      type: string
    - name: SONAR_URL
      default: 'http://sonar.{{ .Release.Namespace }}:9000'
      description: SonarQube url for static code analysis
      type: string
    - name: NEXUS_URL
      default: 'http://nexus.{{ .Release.Namespace }}:8081'
      description: Nexus url
      type: string
    - name: CODEBASE_NAME
      default: 'java11-maven'
      description: "Project name"
      type: string
    - name: CODEBASEBRANCH_NAME
      description: "Codebasebranch name"
      type: string
    - name: maven-image-version
      default: 'maven:3.8.6-openjdk-11-slim'
      description: "maven image version"
      type: string
  tasks:

{{- include "gitlab-build-start" . | nindent 4 }}

    - name: get-version
      taskRef:
        name: get-version-maven-default
      runAfter:
        - init-values
      params:
        - name: BRANCH_NAME
          value: $(params.git-source-revision)
        - name: NEXUS_URL
          value: $(params.NEXUS_URL)
        - name: BASE_IMAGE
          value: $(params.maven-image-version)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: compile
      taskRef:
        name: maven
      runAfter:
        - get-version
      params:
        - name: MAVEN_IMAGE
          value: $(params.maven-image-version)
        - name: GOALS
          value:
            - -B
            - '-Dartifactory.baseUrl=$(params.NEXUS_URL)'
            - '-Dartifactory.releasePath=edp-maven-releases'
            - '-Dartifactory.snapshotsPath=edp-maven-snapshots'
            - '-Dartifactory.groupPath=edp-maven-group'
            - compile
      workspaces:
        - name: source
          workspace: shared-workspace

{{- include "java-maven-build-common" . | nindent 4 }}

{{ include "build-pipeline-lib-end" . | nindent 4 }}

{{ end }}
