{{- define "gerrit-common" -}}
- name: commit-validate
  taskRef:
    kind: Task
    name: commit-validate
  runAfter:
    - fetch-repository
  params:
    - name: COMMIT_MESSAGE_PATTERN
      value: $(params.COMMIT_MESSAGE_PATTERN)
    - name: COMMIT_MESSAGE
      value: $(params.COMMIT_MESSAGE)
  workspaces:
    - name: source
      workspace: shared-workspace

- name: helm-docs
  taskRef:
    kind: Task
    name: golang
  runAfter:
    - init-values
  params:
    - name: EXTRA_COMMANDS
      value: |
        GOPROXY=$(params.GOPROXY) make validate-docs
    - name: BASE_IMAGE
      value: "golang:1.19.6-bullseye"
  workspaces:
    - name: source
      workspace: shared-workspace

- name: helm-lint
  taskRef:
    kind: Task
    name: helm-lint
  runAfter:
    - fetch-repository
  params:
  - name: CHART_DIR
    value: $(params.deploy-templates-dir)
  workspaces:
    - name: source
      workspace: shared-workspace
{{- end -}}
