{{ if eq .Values.global.gitProvider "gerrit" }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gerrit-helm-argocd-lib-build-edp
  labels:
    {{- include "edp-custom-pipelines.labels" . | nindent 4 }}
spec:
  workspaces:
    - name: shared-workspace
    - name: ssh-creds
  params:
    - default: https://tekton-{{ .Release.Namespace }}.{{ .Values.global.dnsWildCard }}/#/namespaces/$(context.pipelineRun.namespace)/pipelineruns/$(context.pipelineRun.name)
      name: pipelineUrl
      type: string
    - default: https://github.com/epmd-edp/container-kaniko-docker
      description: git url to clone
      name: git-source-url
      type: string
    - default: edp
      description: git revision to checkout (branch, tag, sha, ref…)
      name: git-source-revision
      type: string
    - description: Project name
      name: CODEBASE_NAME
      type: string
    - description: Codebasebranch name
      name: CODEBASEBRANCH_NAME
      type: string
    - default: ''
      description: Ticket name pattern
      name: TICKET_NAME_PATTERN
      type: string
    - default: ''
      description: Pattern to validate a commit message
      name: COMMIT_MESSAGE_PATTERN
      type: string
    - default: ''
      description: Commit message
      name: COMMIT_MESSAGE
      type: string
    - default: ''
      description: Jira Payload
      name: JIRA_ISSUE_METADATA_PAYLOAD
      type: string
    - default: ''
      description: Jira server name
      name: JIRA_SERVER
      type: string
  tasks:

{{- include "gerrit-build-start" . | nindent 4 }}

    - name: get-version
      params:
        - name: CODEBASEBRANCH_NAME
          value: $(params.CODEBASEBRANCH_NAME)
      runAfter:
        - gerrit-notify
      taskRef:
        kind: Task
        name: get-version-edp

    - name: git-tag
      params:
        - name: GIT_USER_EMAIL
          value: edp-ci@edp.ci-user
        - name: GIT_USER_NAME
          value: edp-ci
        - name: GIT_SCRIPT
          value: >
            git tag -a "$(tasks.get-version.results.VCS_TAG)" -m "Tag is added
            automatically by CI user"

            git push --tags
      runAfter:
        - get-version
      taskRef:
        kind: Task
        name: git-cli
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: ssh-directory
          workspace: ssh-creds

{{ include "finally-block-edp" . | nindent 2 }}

{{ include "send-to-microsoft-teams-build" . | nindent 4 }}

{{ end }}
