{{ if eq .Values.global.gitProvider "gerrit" }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gerrit-tekton-other-app-review
  labels:
    {{- include "edp-custom-pipelines.labels" . | nindent 4 }}
spec:
  workspaces:
    - name: shared-workspace
    - name: ssh-creds
  params:
    - name: pipelineUrl
      default: https://tekton-{{ .Release.Namespace }}.{{ .Values.global.dnsWildCard }}/#/namespaces/$(context.pipelineRun.namespace)/pipelineruns/$(context.pipelineRun.name)
      type: string
    - name: git-source-url
      default: "https://github.com/epmd-edp/go-go-beego"
      description: git url to clone
      type: string
    - name: git-source-revision
      description: 'git revision to checkout (branch, tag, sha, ref…)'
      default: "edp"
      type: string
    - name: git-refspec
      description: Refspec to fetch before checking out revision.
      default: ""
      type: string
    - name: SONAR_URL
      default: 'http://sonar.{{ .Release.Namespace }}:9000'
      description: SonarQube url for static code analysis
      type: string
    - name: CODEBASE_NAME
      default: "golang-go"
      description: "Project name"
      type: string
    - name: go-image-version
      default: 'golang:1.19.6-bullseye'
      description: "go image with make installed"
      type: string
    - name: GOPROXY
      default: "http://athens-athens-proxy:80"
      description: "Go proxy link"
      type: string
    - name: targetBranch
      description: Target branch of Merge Request
    - name: changeNumber
      description: Change number from Merge Request
    - name: patchsetNumber
      description: Patchset number from Merge Request
    - name: COMMIT_MESSAGE
      description: "Commit message"
    - name: COMMIT_MESSAGE_PATTERN
      description: "Pattern to validate a commit message"
  tasks:

{{- include "gerrit-review-start" . | nindent 4 }}

    - name: commit-validate
      taskRef:
        kind: Task
        name: commit-validate
      runAfter:
        - fetch-repository
      params:
        - name: COMMIT_MESSAGE_PATTERN
          value: $(params.COMMIT_MESSAGE_PATTERN)
        - name: COMMIT_MESSAGE
          value: $(params.COMMIT_MESSAGE)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: helm-docs
      taskRef:
        kind: Task
        name: golang
      runAfter:
        - commit-validate
      params:
        - name: EXTRA_COMMANDS
          value: |
            GOPROXY=$(params.GOPROXY) make validate-docs
        - name: BASE_IMAGE
          value: "golang:1.19.6-bullseye"
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: helm-lint
      taskRef:
        kind: Task
        name: helm-lint
      runAfter:
        - commit-validate
      params:
      - name: EXTRA_COMMANDS
        value: |
          helm repo add epamedp https://epam.github.io/edp-helm-charts/stable --force-update
          helm repo update
          ct lint --all --validate-maintainers=false
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: crdocs-build
      taskRef:
        kind: Task
        name: crdocs
      runAfter:
        - commit-validate
      params:
        - name: BASE_IMAGE
          value: $(params.go-image-version)
        - name: GOPROXY
          value: $(params.GOPROXY)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build
      taskRef:
        kind: Task
        name: golang
      runAfter:
        - helm-docs
      params:
        - name: BASE_IMAGE
          value: $(params.go-image-version)
        - name: GOPROXY
          value: $(params.GOPROXY)
        - name: EXTRA_COMMANDS
          value: |
            make build
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: test
      taskRef:
        kind: Task
        name: golang
      runAfter:
        - build
      params:
        - name: BASE_IMAGE
          value: 'epamedp/tekton-python-make:0.1.2'
        - name: GOPROXY
          value: $(params.GOPROXY)
        - name: EXTRA_COMMANDS
          value: |
            make test
      workspaces:
        - name: source
          workspace: shared-workspace

    # The fetch-target-branch Task will fetch the target branch during the code-review pipeline
    # because the fetch-repository Task fetches only user changes.
    - name: fetch-target-branch
      taskRef:
        kind: Task
        name: git-cli
      runAfter:
        - test
      params:
        - name: GIT_USER_EMAIL
          value: edp-ci@edp.ci-user
        - name: GIT_USER_NAME
          value: edp-ci
        - name: GIT_SCRIPT
          value: |
            git fetch origin $(params.targetBranch):refs/remotes/origin/$(params.targetBranch)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: ssh-directory
          workspace: ssh-creds

    - name: sonar-prepare-files
      taskRef:
        kind: Task
        name: sonar-prepare-files-general
      runAfter:
        - fetch-target-branch
      params:
        - name: CODEBASE_NAME
          value: $(params.CODEBASE_NAME)
        - name: BRANCH_NAME
          value: $(params.targetBranch)
        - name: NORMALIZED_BRANCH
          value: $(tasks.init-values.results.NORMALIZED_BRANCH)
        - name: CHANGE_NUMBER
          value: $(params.changeNumber)
        - name: PATCHSET_NUMBER
          value: $(params.patchsetNumber)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: sonar
      taskRef:
        kind: Task
        name: sonarqube-scanner
      runAfter:
        - sonar-prepare-files
      params:
        - name: SONAR_HOST_URL
          value: $(params.SONAR_URL)
        - name: SONAR_PROJECT_KEY
          value: $(tasks.sonar-prepare-files.results.SONAR_PROJECT_KEY)
        - name: SONAR_PROJECT_NAME
          value: $(tasks.sonar-prepare-files.results.SONAR_PROJECT_KEY)
        - name: SONAR_SOURCES
          value: $(tasks.sonar-prepare-files.results.SONAR_SOURCES)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: dockerfile-lint
      taskRef:
        kind: Task
        name: hadolint
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: dockerbuild-verify
      taskRef:
        kind: Task
        name: dockerbuild-verify
      runAfter:
        - sonar
        - dockerfile-lint
      workspaces:
        - name: source
          workspace: shared-workspace

{{ include "gerrit-review-vote" . | nindent 2 }}

{{ end }}