apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-ingress
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  params:
    - name: ExternalDomain
      description: "The external domain for the EventListener"
    - name: Service
      description: "The name of the Service used in the Ingress. This will also be the name of the Ingress."
    - name: ServicePort
      description: "The service port that the ingress is being created on"
      default: "8080"
    - name: ServiceNamespace
      default: ""
  steps:
    - name: create-ingress
      image: bitnami/kubectl:1.24.4
      script: |
        #!/usr/bin/env bash
        set -e
        cat <<EOF | kubectl create -f - || true
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: $(params.Service)
          namespace: $(params.ServiceNamespace)
        spec:
          rules:
          - host: $(params.ExternalDomain)
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: $(params.Service)
                    port:
                      number: $(params.ServicePort)
        EOF
