apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-autotests-gradle
spec:
  workspaces:
    - name: source
      description: A workspace that contains the repository.
  params:
    - name: stage-name
      type: string
  steps:
    - name: run-autotest
      image: gradle:7.5.1-jdk8
      workingDir: $(workspaces.source.path)
      env:
        - name: STAGE_NAME
          value: $(params.stage-name)
      script: |
        $(sed -n 's/.*"'$STAGE_NAME'": "\(.*\)",/\1/p' run.json | awk -F '"' '{print $1}')
{{- include "resources" . | nindent 6 }}
