apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-triggers-edp-interceptor
  labels:
    {{- include "edp-tekton-interceptor.labels" . | nindent 4 }}
rules:
  - verbs:
      - get
      - list
      - watch
      - update
    apiGroups:
      - triggers.tekton.dev
    resources:
      - clusterinterceptors

  - verbs:
      - get
      - list
      - watch
      - update
    apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - tekton-triggers-core-interceptors-certs

  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - secrets

  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - v2.edp.epam.com
    resources:
      - codebases
      - codebases/status
      - codebases/finalizers
