apiVersion: v1
kind: Service
metadata:
  name: tekton-triggers-edp-interceptor
  namespace: {{ .Values.tektonNamespace }}
  labels:
    {{- include "edp-tekton-interceptor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "edp-tekton-interceptor.selectorLabels" . | nindent 4 }}
