apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "edp-tekton-interceptor.serviceAccountName" . }}
  namespace: {{ .Values.tektonNamespace }}
  labels:
    {{- include "edp-tekton-interceptor.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
