apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cd-stage-deploy
spec:
  params:
    - name: CDPIPELINE
      description: |
        EDP kind:CDPipeline name used for deployment. For example: mypipe, myfeature
    - name: CDSTAGE
      description: |
        EDP kind:Stage name of the kind:CDPipeline defined in the CDPIPELINE values. For example: dev, test, prod
    - name: APPLICATIONS_PAYLOAD
      description: |
        Applications payload in format: '{"codebase1": "version1", "codebase2": "version2"}. For example: '{"demo": "main-20240103-141431", "myapp": "0.1.0-SNAPSHOT.1"}'
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: deploy-$(tt.params.CDPIPELINE)-$(tt.params.CDSTAGE)-
        labels:
          app.edp.epam.com/cdpipeline: $(tt.params.CDPIPELINE)
          app.edp.epam.com/cdstage: $(tt.params.CDSTAGE)
          app.edp.epam.com/pipelinetype: deploy
      spec:
        taskRunTemplate:
          serviceAccountName: tekton
        pipelineRef:
          name: cd-stage-deploy
        params:
          - name: APPLICATIONS_PAYLOAD
            value: $(tt.params.APPLICATIONS_PAYLOAD)
          - name: CDSTAGE
            value: $(tt.params.CDSTAGE)
          - name: CDPIPELINE
            value: $(tt.params.CDPIPELINE)
        timeouts:
          pipeline: 1h00m0s
