kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: security
  name: tekton-autotests-{{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
