{{- if ne .Values.global.gitProvider "gerrit" -}}
{{ if eq .Values.global.platform "kubernetes" }}
{{- $elName := printf "el-%s-listener" .Values.global.gitProvider -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $elName }}
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
  {{- with .Values.eventListener.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.eventListener.ingress.tls }}
  tls:
    {{- range .Values.eventListener.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $elName }}-{{ .Release.Namespace }}.{{ .Values.global.dnsWildCard }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $elName }}
                port:
                  number: 8080
{{- end }}
{{- end }}
