{{- if ne .Values.global.gitProvider "gerrit" -}}
{{ if eq .Values.global.platform "kubernetes" }}
{{- if .Values.eventListener.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-listener
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
  {{- with .Values.eventListener.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.eventListener.ingress.tls }}
  tls:
    {{- range .Values.eventListener.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: el-{{ .Release.Namespace }}.{{ .Values.global.dnsWildCard }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # The service name will come from EventListener CR
                name: edp
                port:
                  number: 8080
{{- end }}
{{- end }}
{{- end }}
