{{- if eq .Values.global.platform "openshift" -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
  name: tekton-registry-editor
subjects:
  - kind: ServiceAccount
    name: tekton
    namespace: {{ .Values.global.edpName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-editor
{{- end -}}
