{{- if not (has "gerrit" .Values.global.gitProviders) -}}
{{ if eq .Values.global.platform "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: event-listener
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
  {{- with .Values.eventListener.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
    host: el-{{ .Release.Namespace }}.{{ .Values.global.dnsWildCard }}
    tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
    to:
        kind: Service
        name: el-edp
        weight: 100
    port:
      targetPort: http-listener
    wildcardPolicy: None
{{- end }}
{{- end }}
