apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
  {{- if .Values.kaniko.roleArn  }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.kaniko.roleArn }}
  {{ end }}
