{{ if eq .Values.global.gitProvider "github" }}
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  triggers:
    - name: github-listener-build
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.github.webhook.existingSecret }}
                secretKey: secretString
            - name: "eventTypes"
              value: ["pull_request"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['closed']"
        - ref:
            name: "edp"
            kind: NamespacedInterceptor
        - ref:
            name: "cel"
          params:
            - name: "overlays"
              value:
                - key: cbtype_short
                  expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: github-binding-build
      template:
        ref: github-build-template

    - name: github-listener-review
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.github.webhook.existingSecret }}
                secretKey: secretString
            - name: "eventTypes"
              value: ["pull_request"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'edited']"
        - ref:
            name: "edp"
            kind: NamespacedInterceptor
        - ref:
            name: "cel"
          params:
            - name: "overlays"
              value:
              - key: cbtype_short
                expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: github-binding-review
      template:
        ref: github-review-template

  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-sa-{{ .Release.Namespace }}
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "0.05"
                  limits:
                    memory: "128Mi"
                    cpu: "0.5"
{{ end }}
