{{ if .Values.github.enabled }}
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  triggers:
    - name: github-listener-autotests-build
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.github.webhook.existingSecret }}
                secretKey: {{ .Values.github.webhook.secretKeys.secretKey }}
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: cel
          params:
            - name: "overlays"
              value:
                - key: branch_name
                  expression: "body.ref.split('/')[2]"
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.branch_name in ['edp','main','master']"
        - ref:
            name: "edp"
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.spec.type in ['autotests']"
            - name: "overlays"
              value:
                - key: cbtype_short
                  expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: github-binding-build
      template:
        ref: github-build-lib-autotests-template

    - name: github-listener-app-build
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.github.webhook.existingSecret }}
                secretKey: {{ .Values.github.webhook.secretKeys.secretKey }}
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: cel
          params:
            - name: "overlays"
              value:
                - key: branch_name
                  expression: "body.ref.split('/')[2]"
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.branch_name in ['edp','main','master']"
        - ref:
            name: "edp"
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.spec.type in ['application']"
            - name: "overlays"
              value:
              - key: cbtype_short
                expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: github-binding-build
      template:
        ref: github-build-app-template

    - name: github-listener-lib-build
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.github.webhook.existingSecret }}
                secretKey: {{ .Values.github.webhook.secretKeys.secretKey }}
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: cel
          params:
            - name: "overlays"
              value:
                - key: branch_name
                  expression: "body.ref.split('/')[2]"
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.branch_name in ['edp','main','master']"
        - ref:
            name: "edp"
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.spec.type in ['library'] && extensions.spec.framework != 'docker'"
            - name: "overlays"
              value:
                - key: cbtype_short
                  expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: github-binding-build
      template:
        ref: github-build-lib-autotests-template

    - name: github-listener-container-build
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.github.webhook.existingSecret }}
                secretKey: {{ .Values.github.webhook.secretKeys.secretKey }}
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: cel
          params:
            - name: "overlays"
              value:
                - key: branch_name
                  expression: "body.ref.split('/')[2]"
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.branch_name in ['edp','main','master']"
        - ref:
            name: "edp"
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.spec.type in ['library'] && extensions.spec.framework == 'docker'"
            - name: "overlays"
              value:
                - key: cbtype_short
                  expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: github-binding-build
      template:
        ref: github-build-app-template

    - name: github-listener-app-container-code-review
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.github.webhook.existingSecret }}
                secretKey: {{ .Values.github.webhook.secretKeys.secretKey }}
            - name: "eventTypes"
              value: ["pull_request"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'edited']"
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.pull_request.base.ref in ['edp','main','master']"
        - ref:
            name: "cel"
          params:
            - name: "overlays"
              value:
                - key: branch_name
                  expression: "body.pull_request.head.ref"
        - ref:
            name: "edp"
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.spec.type in ['application'] || (extensions.spec.type in ['library'] && extensions.spec.framework == 'docker')"
            - name: "overlays"
              value:
              - key: cbtype_short
                expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: github-binding-review
      template:
        ref: github-code-review-app-container-template

    - name: github-listener-lib-autotests-code-review
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: {{ .Values.github.webhook.existingSecret }}
                secretKey: {{ .Values.github.webhook.secretKeys.secretKey }}
            - name: "eventTypes"
              value: ["pull_request"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'edited']"
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.pull_request.base.ref in ['edp','main','master']"
        - ref:
            name: "cel"
          params:
            - name: "overlays"
              value:
                - key: branch_name
                  expression: "body.pull_request.head.ref"
        - ref:
            name: "edp"
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "extensions.spec.type in ['autotests'] || (extensions.spec.type in ['library'] && extensions.spec.framework != 'docker')"
            - name: "overlays"
              value:
                - key: cbtype_short
                  expression: "extensions.spec.type.truncate(3)"
      bindings:
        - ref: github-binding-review
      template:
        ref: github-code-review-lib-autotests-template

  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-sa-{{ .Release.Namespace }}
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "50m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
{{ end }}
