{{ if eq .Values.global.gitProvider "github" }}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding-build
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  params:
    - name: gitrevision
      value: "$(extensions.branch_name)"
    - name: gitrepositoryurl
      value: "$(body.repository.ssh_url)"
    - name: gitrepositoryname
      value: "$(body.repository.name)"
    - name: buildtool
      value: "$(extensions.spec.buildTool)"
    - name: framework
      value: "$(extensions.spec.framework)"
    # Truncated cbtype type name to reduce string length
    - name: cbtype
      value: "$(extensions.cbtype_short)"
    - name: versioning-type
      value: "$(extensions.spec.versioning.type)"
    - name: commitMessagePattern
      value: "$(extensions.spec.commitMessagePattern)"
    - name: codebase
      value: "$(extensions.codebase)"
    - name: codebasebranch
      value: "$(extensions.codebasebranch)"
{{ end }}
