{{ if .Values.github.enabled }}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-code-review-app-container-template
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
    - name: gitrepositoryname
    - name: gitfullrepositoryname
    - name: gitsha
    - name: buildtool
      description: Build tool for codebase. Used to generate code-review pipeline name. Populated by edp interceptor
    - name: framework
      description: Framework for codebase. Used to generate code-review pipeline name. Populated by edp interceptor
    - name: cbtype
      description: Application or library type for codebase. Used to generate build pipeline name. Populated by edp interceptor
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.gitrepositoryname)-review-
      spec:
        serviceAccountName: tekton
        taskRunSpecs:
          - pipelineTaskName: dockerbuild-verify
            taskServiceAccountName: edp-kaniko
        pipelineRef:
          name: github-$(tt.params.buildtool)-$(tt.params.framework)-$(tt.params.cbtype)-review
        params:
          - name: git-source-url
            value: $(tt.params.gitrepositoryurl)
          - name: git-source-revision
            value: $(tt.params.gitrevision)
          - name: CODEBASE_NAME
            value: $(tt.params.gitrepositoryname)
          - name: gitfullrepositoryname
            value: $(tt.params.gitfullrepositoryname)
          - name: gitsha
            value: $(tt.params.gitsha)
        workspaces:
          - name: settings
            configMap:
              name: custom-$(tt.params.buildtool)-settings
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
            subPath: codebase
          - name: ssh-creds
            secret:
              secretName: {{ .Values.github.webhook.existingSecret }}
{{ end }}
